apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-intro
  name: devops-intro
spec:
  selector:
    matchLabels: devops-intro
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80