apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: devops-intro
build:
  artifacts:
  - image: myimage
    context: src
    docker:
      dockerfile: Dockerfile
      target: development
    sync:
      infer:
      - '**/*.py'
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
